spring:
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB}
        username: ${POSTGRES_USER:springUser}
        password: ${POSTGRES_PASSWORD:springPassword}